### 1. Import the NUMPY package under the name np and PANDAS as pd.

In [3]:
import numpy as np
import pandas as pd

### 2. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"

In [6]:
a = np.random.random((2,3,5))
a

array([[[0.64484007, 0.10351365, 0.67688934, 0.22794002, 0.80758486],
        [0.80220609, 0.64907674, 0.03185046, 0.77406916, 0.52351393],
        [0.08211341, 0.52108608, 0.34214124, 0.71791305, 0.28873095]],

       [[0.48241601, 0.69866666, 0.24988858, 0.57523001, 0.19184293],
        [0.97633767, 0.86981558, 0.83693923, 0.27363085, 0.89931557],
        [0.3403542 , 0.39668999, 0.50310052, 0.14213196, 0.59800711]]])

### 3. Create a 5x2x3 3-dimensional array with all values equaling 1.

In [9]:
b = np.ones((5,2,3))
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

### 4. Do a and b have the same size? How do you prove that in Python code?

In [12]:
a.size == b.size


True

### 4. Identify the max, min, and mean values in a. Assign those values to variables "d_max", "d_min", and "d_mean"

In [15]:
a_max = a.max()
a_min = a.min()
a_mean = a.mean()
print(a_max)
print(a_min)
print(a_mean)

0.9763376661872388
0.031850461036896816
0.5075945312067321


### 5. Now we want to label the values in a. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

In [19]:
f = np.empty((2, 3, 5))
f

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

### 6. Populate the values in f. 

    For each value in a, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
    If a value in a is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
    If a value equals to d_mean, assign 50 to the corresponding value in f.
    Assign 0 to the corresponding value(s) in f for d_min in d.
    Assign 100 to the corresponding value(s) in f for d_max in d.
    In the end, f should have only the following values: 0, 25, 50, 75, and 100.
    Note: you don't have to use Numpy in this question.

In [33]:
for i in range(2):
    for j in range(3):
        for h in range(5):
            if a_min < a[i][j][h] < a_mean:
                f[i][j][h] = 25
            elif a_mean < a[i][j][h] < a_max:
                f[i][j][h] = 75
            elif a[i][j][h] == a_mean:
                f[i][j][h] = 50
            elif a[i][j][h] == a_min:
                f[i][j][h] = 0
            elif a[i][j][h] == a_max:
                f[i][j][h] = 100
print(f'\n{a}')
print(f'\n{f}')


[[[0.64484007 0.10351365 0.67688934 0.22794002 0.80758486]
  [0.80220609 0.64907674 0.03185046 0.77406916 0.52351393]
  [0.08211341 0.52108608 0.34214124 0.71791305 0.28873095]]

 [[0.48241601 0.69866666 0.24988858 0.57523001 0.19184293]
  [0.97633767 0.86981558 0.83693923 0.27363085 0.89931557]
  [0.3403542  0.39668999 0.50310052 0.14213196 0.59800711]]]

[[[ 75.  25.  75.  25.  75.]
  [ 75.  75.   0.  75.  75.]
  [ 25.  75.  25.  75.  25.]]

 [[ 25.  75.  25.  75.  25.]
  [100.  75.  75.  25.  75.]
  [ 25.  25.  25.  25.  75.]]]


Print a and f. 

Do you have your expected f?

For instance, if your a is:

    array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:

    array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],
       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])

### 7. Create a Pandas DataFrame from the list of lists below. Each sublist should be represented as a row.

In [35]:
matriz = [[53.1, 95.0, 67.5, 35.0, 78.4],
     [61.3, 40.8, 30.8, 37.8, 87.6],
     [20.6, 73.2, 44.2, 14.6, 91.8],
     [57.4, 0.1, 96.1, 4.2, 69.5],
     [83.6, 20.5, 85.4, 22.8, 35.9],
     [49.0, 69.0, 0.1, 31.8, 89.1],
     [23.3, 40.7, 95.0, 83.8, 26.9],
     [27.6, 26.4, 53.8, 88.8, 68.5],
     [96.6, 96.4, 53.4, 72.4, 50.1],
     [73.7, 39.0, 43.2, 81.6, 34.7]]
df = pd.DataFrame(matriz)
df

0     1     2     3     4
0  53.1  95.0  67.5  35.0  78.4
1  61.3  40.8  30.8  37.8  87.6
2  20.6  73.2  44.2  14.6  91.8
3  57.4   0.1  96.1   4.2  69.5
4  83.6  20.5  85.4  22.8  35.9
5  49.0  69.0   0.1  31.8  89.1
6  23.3  40.7  95.0  83.8  26.9
7  27.6  26.4  53.8  88.8  68.5
8  96.6  96.4  53.4  72.4  50.1
9  73.7  39.0  43.2  81.6  34.7

### 8. Rename the data frame columns based on the names in the list below.

In [38]:
colnames = ['Score_1', 'Score_2', 'Score_3', 'Score_4', 'Score_5']
df.columns = colnames
df

Score_1  Score_2  Score_3  Score_4  Score_5
0     53.1     95.0     67.5     35.0     78.4
1     61.3     40.8     30.8     37.8     87.6
2     20.6     73.2     44.2     14.6     91.8
3     57.4      0.1     96.1      4.2     69.5
4     83.6     20.5     85.4     22.8     35.9
5     49.0     69.0      0.1     31.8     89.1
6     23.3     40.7     95.0     83.8     26.9
7     27.6     26.4     53.8     88.8     68.5
8     96.6     96.4     53.4     72.4     50.1
9     73.7     39.0     43.2     81.6     34.7

### 9. Create a subset of this data frame that contains only the Score 1, 3, and 5 columns.

In [39]:
df1 = df[['Score_1', 'Score_3', 'Score_5']]
df1

Score_1  Score_3  Score_5
0     53.1     67.5     78.4
1     61.3     30.8     87.6
2     20.6     44.2     91.8
3     57.4     96.1     69.5
4     83.6     85.4     35.9
5     49.0      0.1     89.1
6     23.3     95.0     26.9
7     27.6     53.8     68.5
8     96.6     53.4     50.1
9     73.7     43.2     34.7

### 10. From the original data frame, calculate the average Score_3 value.

In [41]:
mean3 = df['Score_3'].mean()
mean3

56.95000000000001

### 11. Create a Pandas DataFrame from the dictionary of product orders below.

In [42]:
orders = {'Description': ['LUNCH BAG APPLE DESIGN',
  'SET OF 60 VINTAGE LEAF CAKE CASES ',
  'RIBBON REEL STRIPES DESIGN ',
  'WORLD WAR 2 GLIDERS ASSTD DESIGNS',
  'PLAYING CARDS JUBILEE UNION JACK',
  'POPCORN HOLDER',
  'BOX OF VINTAGE ALPHABET BLOCKS',
  'PARTY BUNTING',
  'JAZZ HEARTS ADDRESS BOOK',
  'SET OF 4 SANTA PLACE SETTINGS'],
 'Quantity': [1, 24, 1, 2880, 2, 7, 1, 4, 10, 48],
 'UnitPrice': [1.65, 0.55, 1.65, 0.18, 1.25, 0.85, 11.95, 4.95, 0.19, 1.25],
 'Revenue': [1.65, 13.2, 1.65, 518.4, 2.5, 5.95, 11.95, 19.8, 1.9, 60.0]}

In [43]:
df2 = pd.DataFrame(orders)
df2

Description  Quantity  UnitPrice  Revenue
0              LUNCH BAG APPLE DESIGN         1       1.65     1.65
1  SET OF 60 VINTAGE LEAF CAKE CASES         24       0.55    13.20
2         RIBBON REEL STRIPES DESIGN          1       1.65     1.65
3   WORLD WAR 2 GLIDERS ASSTD DESIGNS      2880       0.18   518.40
4    PLAYING CARDS JUBILEE UNION JACK         2       1.25     2.50
5                      POPCORN HOLDER         7       0.85     5.95
6      BOX OF VINTAGE ALPHABET BLOCKS         1      11.95    11.95
7                       PARTY BUNTING         4       4.95    19.80
8            JAZZ HEARTS ADDRESS BOOK        10       0.19     1.90
9       SET OF 4 SANTA PLACE SETTINGS        48       1.25    60.00

### 12. Calculate the total quantity ordered and revenue generated from these orders.

In [44]:
quantity = df2['Quantity'].sum()
print(f'Total quantity ordered: {quantity}')
revenue = df2['Revenue'].sum()
print(f'Total revenue ordered: {revenue}')

Total quantity ordered 2978
Total revenue ordered 637.0
